### PR TITLE
MatNavMenu - New component

### PR DESCRIPTION
**Pull request by enkodellc**
A navigation component based off of the accordion / expansion panel. Currently works for 2 levels. Need some modifications to do 2+ levels. I updated the Demo menu with the new NavMenu and categorized the components in a similar fashion to Angular Material. https://material.angular.io/components/categories

### CODE REVIEW

**Comment by SamProf** [comment]
Looks very nice. Thank you!

But before release of this component, can you fix little visual bug.

image


On hover and click sub-headers have 2 borders - that's ok? I feel something wrong.

**Comment by iAmBipinPaul** [comment]
does this work without JavaScript?
I mean most case `NavMenu` will be rendered on server.

**Comment by enkodellc** [comment]
@SamProf I will take a look at the double on Menu hover issue. That is one area that I was thinking might need some outside eyes to review. The MatNavSubPanel / Header...  you can use a MatNavItem, which causes the double border or Text... If you have time take a deeper looks and see if you have some other ideas on it. I felt this was a great start. I didn't go far into 2+ levels or a flyout style but with this start maybe others can build on top of it?

@iAmBipinPaul the NavMenu is a combination of the Accordion / Expansion Panel / List Item.  Most of the rendering is in the Material Javascript.  The StateChanged [Expanded / Selected] is most likely calling Server Side if you are running that type of Blazor project.

**Comment by whentotrade** [comment]
Great! 

I discovered that the OnClick="...." event for the <MatNavItem...> does not work. The OnClick function is not executed. Is this a missing event?

**Comment by enkodellc** [comment]
@whentotrade Well yes and No. The MatNavItem inherits from MatListItem and uses that OnClick and was designed to do redirect to a page. I understand you wish to do something else with the OnClick. So  a possible solution is to create a "OnNavClick" property to handle another click event.  Take a look at the code and see if you can create that and get the solution you want and submit a PR. The code is not terribly difficult. I am trying to get more people to contribute and not just do functionality they ask for as that is our time and resources.  Another option for motivation for us to spend our time on custom functionality is to sponsor / donate to  @SamProf  or me on https://blazorboilerplate.com/.  Thanks!

**Pull request merged**
