### PR TITLE
.Nuget updates / NET Core 3.2 Preview 1

### PR DESCRIPTION
**Pull request by enkodellc**
.Nuget updates / NET Core 3.2 Preview 1 and Nuget Package updates. 

For some reason if I have .Nuget updates / NET Core 3.2 Preview 1 in Blazor Boilerplate and use 2.0.1 with .Net Core 3.1 my menu is messed up.  Maybe this will help you out. 

Basically delete Startup.cs and move some of that to the Program.cs

### CODE REVIEW

**Comment by SamProf** [comment]
Yeah! Thank you! This will be in release at Monday.

**Comment by khenzar** [comment]
Hello, does this mean we can't use the latest version of MatBlazor if we wish to stay on .NET Core 3.1 ?

**Comment by RonPeters** [comment]
I don't understand why dependencies were made on a preview of .NET Core. Now none of us can use this and deploy on production .NET Core. I think this was a bad call.

**Comment by SamProf** [comment]
Ok, today we will move back

**Comment by enkodellc** [comment]
@SamProf My opinion is we should be on the leading edge of releases.  I know there has to be a lot of people who want the latest release as well as other's who in production. 

I know I had MatBlazor issues in 3.1 and my app was on Preview 3.2 Preview 1.  Either way it will cause issues for some group of people.

**Comment by enkodellc** [comment]
@SamProf I was just about to suggest that. Can do a preview release. Not sure how much more work it is?

**Comment by RonPeters** [comment]
@enkodellc I understand the desire, but some of us are using this in production on Azure and also need the incremental fixes. It's too bad 3.2 apparently introduces some sort of breaking change. I really hope we can figure out something to support both.

**Comment by SamProf** [comment]
from now we will have 2 releases.

https://www.nuget.org/packages/MatBlazor/2.2.0 (for stable DotNetCore)
https://www.nuget.org/packages/MatBlazor/2.2.0-preview (for Preview version)

Preview will be here https://github.com/SamProf/MatBlazor/tree/preview

**Comment by SamProf** [comment]
@RonPeters @enkodellc Can you check your versions? Thank you!

**Comment by enkodellc** [comment]
Just tested and pushed the preview. Thanks @SamProf

**Comment by GioviQ** [comment]
> from now we will have 2 releases.
> 
> https://www.nuget.org/packages/MatBlazor/2.2.0 (for stable DotNetCore)
> https://www.nuget.org/packages/MatBlazor/2.2.0-preview (for Preview version)
> 
> Preview will be here https://github.com/SamProf/MatBlazor/tree/preview

nuget does not understand that 2.2.0 is not an upgrade of 2.2.0-preview, it would be better to increase version, e.g. 2.2.1-preview

**Pull request merged**
