### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by damianog**
Code cleanup and removed redundat base class

### CODE REVIEW

**Comment by damianog** [comment]
Hi @enkodellc  could PR this?

**Comment by enkodellc** [comment]
Honestly I think @SamProf  should evaluate this. He wrote the base class so maybe he had a reason. If not then I would agree to lean it out.

**Comment by damianog** [comment]
I supposed so too, maybe for a ButtonLink, actually these base class are not used. Learning to use Blazor I have seen many examples of components built with base classes and in the most recent period extending the html component with a partial class (which I find more elegant) and I see the same change of style in latest MatBlazor compontents, but this is my opinion, obviously @SamProf has the last word 😃

**Comment by enkodellc** [comment]
Personally, I would like to see you devote more of your energy on resolving issues or testing PR's and offering your opinion on them. I am not saying we should not be doing a code review / refactor but I think issues / PR's have a higher priority. Just my 2 cents. We appreciate any help!

**Comment by damianog** [comment]
@enkodellc yeah it will be for sure, sorry I do not want create confusion, usually before starting to fix I start to clean so I even learn how the code has been conceived. MatBlazor is great big project. My apologies again.

**Comment by SamProf** [comment]
Hey. Thank you for this contrubution.
`Base*` classes was created at time when Blazor not supports `partial` components. At this time this was standard codestyle for Blazor.
Now - yes using of `partail` classes is better way.
But I expect that I will make this refactoring, because It's much easier to make myself then check is it all right. =)

But I will merge this PR - thank you!

**Pull request merged**
