### PR TITLE
Input improvements

### LINKED ISSUE #365: MatBlazorSwitchT - Missing some implementations for nullable types
First of all, thank you for your amazing library. Very useful in my project.

I noticed that when I bind `MatTextField` to a `int?` property, it fails at runtime with a `NullReferenceException`.

After looking deeper, I realized that you don't propose any implementation for `int?` in your class `MatBlazorSwitchT`. It's the same for `byte`, `float` and `double`.

Not a big deal to add I hope...

### PR DESCRIPTION
**Pull request by RonPeters**
I haven't seen @SamProf on here in at least 2 weeks. I hope all is well.

I will just keep adding my commits to this pull request until there is more merge activity on this repo.

- MatIconButton - Added OnClickStopPropagation
- MatButton - Added OnClickStopPropagation
- MatDatePicker - Do not display the time in the text field by default. Respect the Format and EnableTime parameters.
- MatDatePicker - Fixed the labeling of the DisableMobile Demo
- MatDatePicker - Fixed Minimum and Maximum implementation by comparing only dates if EnableTime is false, and comparing dates and times if EnableTime is true
- MatNumericUpDownField - Added FieldType parameter with Numeric, Currency, and Percent types. Percent was needed as a special implementation because the .NET percent format string multiplies the value by 100. This means 0.45 displays as 45%. So I had to hook into the parsing so that when you entered "45", it was converted to the value 0.45. Updated the demo to reflect the new FieldType
- MatBlazorSwitchT - Merged PR #449 [Add MatBlazorSwitchT implementations for nullable primitive types Resolves #365]
- package.json - Fixed invalid structure and updated some packages to address some of the vulnerabilities identified in audit

### CODE REVIEW

**Comment by RonPeters** [comment]
I just @fire-birdie comment that "I ran into this problem while trying to bind MatNumericUpDownField to an int? field. Looking at the 2.0.0 release notes makes it seem like the decision to omit support for non-decimal nullable types was intentional, but I can't figure out why. I'll prepare a PR to add support for the other primitive types, I just hope it doesn't break anything..."

I needed int? support as well, so I merged that PR. If it causes problems, can we just keep int? support without breaking other things?

**Comment by enkodellc** [comment]
Thanks for contributing Ron!!

**Comment by RonPeters** [comment]
I'm trying to get to production quality on inputs and tables. More to come!

**Comment by RonPeters** [comment]
I just made the last update to this PR. I was going to make separate PRs, but then I realized that the updates built on each other, so it was easier to just update this branch. Feel free to review and merge.

**Comment by SamProf** [comment]
I am ill, in a 1-3 days I will return =)

**Comment by SamProf** [comment]
Thank you for your big contribution! 
I need time to check this PR. I think tomorrow I will check and will make new release with this changes

**Comment by RonPeters** [comment]
Thank you for this great repo! It has been very useful to me, so the least I can do is contribute back.

**Comment by enkodellc** [comment]
@RonPeters Please fill out a comment on this issue: https://github.com/SamProf/MatBlazor/issues/474   I think you might be a contributor.

**Comment by SamProf** [comment]
Thank you. Visually it's good job.
can you fix merge conflicts here?
'
src/MatBlazor.Demo/Demo/DemoMatTextField.razor
src/MatBlazor.Demo/Demo/DemoNumericUpDownField.razor
'

**Comment by RonPeters** [comment]
@SamProf Thanks, I was just about to merge the conflicts.

**Pull request merged**
