### PR TITLE
Remove extra padding from Toast when not in full-screen

### PR DESCRIPTION
**Pull request by americanslon**
Remove extra padding from Toast when not in full-screen.
Annotation 2020-02-11 103529

### CODE REVIEW

**Comment by SamProf** [comment]
Thank you for your contribution 👍!
But you commit only `src/MatBlazor/wwwroot/dist/matBlazor.css` - this is generated file. Please, commit source code of your styles to apply.

**Comment by americanslon** [comment]
This is the only CSS related style I found in the whole project, I was surprised myself. Is there a scss file or something like that somewhere?

**Comment by SamProf** [comment]
Here is js/scss project for MatBlazor `MatBlazor\src\MatBlazor.Web\`
Here is styles for Toast `MatBlazor\src\MatBlazor.Web\src\matToast\matToast.scss`

**Comment by enkodellc** [comment]
Creating a new PR with the actual edits to matToast.scss.

**Pull request closed without merging**
