### PR TITLE
Fix load paging data to MatTable.

### PR DESCRIPTION
**Pull request by KoJIo63uK**
The current solution does not work and is not logical. I offer my fixes for getting the page object from the api.

### CODE REVIEW

**Comment by KoJIo63uK** [comment]
The current solution does not work and is not logical. I offer my fixes for getting the page object from the api.

**Review by KoJIo63uK — COMMENTED** [review]
Old code doesn't work.

**Comment by SamProf** [comment]
@enkodellc What you think about this?

**Comment by enkodellc** [comment]
Looks good to me.

**Review by enkodellc — APPROVED** [review]

**Comment by SamProf** [comment]
@enkodellc  Somehow you merge this in master =)

**Comment by enkodellc** [comment]
Sorry, I forget to check where the PR was for. Normally I switch to dev if the the contributor didn't follow instructions on readme

**Pull request merged**
