### PR TITLE
Fixes #293 - Adds Paging in Top / Bottom / Both

### LINKED ISSUE #293: Feature Request: Make the location of the paging controls in a MatTable configurable
Hi,

First of all, appreciate the work with the library. Really useful and helped me get going with our first production deployment of a Blazor project really quickly. Great stuff.

However, the Product Owner in my team requested the paging control in MatTable to be configurable (top / bottom / both). I'm looking into this right now myself (already forked your code), and will hopefully submit a PR a bit later - just thought I want to be transparent with the process and let you know.

Cheers!

### PR DESCRIPTION
**Pull request by koskila**
Implements #293 by changing table pagination into a component and making its display configurable (top and footer are now both switches, it's backwards compatible though).

I'm happy this was easier than I thought, great job with structuring the components - it was easy to jump on the task!

### CODE REVIEW

**Comment by Christian-Oleson** [comment]
@koskila ,
There are now conflicts. Can you please fix this?

**Comment by koskila** [comment]
Should be good now @Christian-Oleson . I don't think I made any changes to BaseMatTable.cs, not sure if I inadvertedly changed the line endings (weird if that happened for most rows but not all) which marked the file as modified...

**Comment by Christian-Oleson** [comment]
@koskila , you can probably close this since MatBlazor is pretty much dead

**Comment by koskila** [comment]
Fair enough 😐

**Pull request closed without merging**
