### PR TITLE
Update MatNavItem.razor

### PR DESCRIPTION
**Pull request by americanslon**
This should make MatNavLink indicated selected when url has partial match. Issue #259

### CODE REVIEW

**Comment by enkodellc** [comment]
@americanslon I am afraid there are some opposite negative effects from this change. I am not sure if you tested but changing it to prefix now makes the Home / root link to always be active / highlighted. I would revert this issue and come up with another solution.

**Comment by americanslon** [comment]
@enkodellc The proper solution is likely to allow that field to be set per link. I may do it at some point or maybe it's on the list for the main contributor already, I don't know.

As for reverting I wouldn't do it as it breaks essentially 100% of the applications. If I understand your use case correctly all you have to do to work around it, is have a named home page `\home` and redirect to it from `\` route. If we revert back it breaks the links for any application with route system as such `\organizations\organization` which, I'd imagine, a vast majority of SPAs. There is also no working around that as far as I can see.

As one pointy eared philosopher said "The needs of the many (usecases) outweigh the needs of the few (usecases) :)

**Comment by enkodellc** [comment]
@americanslon I appreciate your feedback and PR. I created the MatNav for MatBlazor and have contributed a lot to MatBlazor. The path match not on the todo list but could easily be done. Vladimir is focused on other controls.

Why did you not implement in the PR to update MatBlazor that redirect's "/" to "home" to fix the now broken active MatNav, currently always showing "Home" as active?  If anything your redirect solution for home should have included this. As well as an update to the MatNav documentation for other's to follow the updated usage / design pattern. As of now you have officially broken MatBlazor and any other apps with the standard "/" root.  For me this is the proper solution and then then "option" is not necessarily needed?

**Comment by americanslon** [comment]
I don't believe it's up to the framework to dictate what people use as their home page. What if you want your home page to be called `noodles`? I would also be very surprised if my widget framework was redirecting things - it just doesn't feel proper. When something requires a workaround however small or logical I don't think it should be hidden in the framework - it should be a choice whether people care enough to implement the workaround or not.

I still maintain that the proper way is to expose that option with the default being `prefix`. That said between two gapstop solutions I think mine is better because the old one officially breaks MatBlazor for EVERY NESTED link without any workarounds.

For what it's worth [`NavLink` uses `prefix` as default ](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1#navlink-component)

**Pull request merged**
