### PR TITLE
Fix null reference exception for multi column filtering in MatTable

### PR DESCRIPTION
**Pull request by akovac35**
Fixed a null reference exception.

### CODE REVIEW

**Comment by SamProf** [comment]
Thank you for contribution.
Maybe this will be also solution?
```
properties.Where(x => x.GetValue(item, null)?.ToString() != null).Select(x => x.GetValue(item, null)?.ToString());
```

**Comment by akovac35** [comment]
I can only comment about my code, please use it because it fixes a problem with multi column filtering.

**Comment by akovac35** [comment]
And the second ? is not needed because the final select is never null.

**Comment by akovac35** [comment]
Can I help with anything related to this merge?

**Comment by enkodellc** [comment]
`var values = properties.Where(x => x.GetValue(item, null)?.ToString() != null).Select(x => x.GetValue(item, null).ToString());`

@akovac35  I like this code, closer to what we have and solves the problem. I think this is what Samprof was thinking. If you want to update your PR for this code I will merge. Your thoughts?

**Review by enkodellc — APPROVED** [review]

**Pull request merged**
