### PR TITLE
MatNumericUpDownField

### PR DESCRIPTION
**Pull request by ctrl-alt-d**
Hi,

this component is base on MatTextField and it has a behavior like [NumericUpDownField](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/numericupdown-control-overview-windows-forms).

You can view the control in action with this code:

```
@page "/NumericUpDownField"

<h4>Counter 1: [@(testingNullableDecimal1?.ToString() ?? "No value")] </h4>
<h4>Counter 2: [@(testingNullableDecimal2?.ToString() ?? "No value")] </h4>

<MatButton OnClick="@Click">ClickMe @ButtonState</MatButton>
<br/>
<MatNumericUpDownField 
        bind-Value=@testingNullableDecimal1 
        DecimalPlaces=2>
</MatNumericUpDownField>
<MatNumericUpDownField 
        bind-Value=@testingNullableDecimal2 
        DecimalPlaces=0 
        Minimum=null Maximum=null >
</MatNumericUpDownField>

@functions
{
  decimal? testingNullableDecimal1 = 0;
  decimal? testingNullableDecimal2 = null;

  string ButtonState = "";
  void Click(UIMouseEventArgs e)
  {
    ButtonState = "Clicked";
    testingNullableDecimal1 += 1;
    testingNullableDecimal2 += 100;
  }
} 
```

I wrote a non-core control because this is my first PR to this project and I want to know if this is the way to contribute. For example, I make the PR to master branch because they are not a "develop branch". Also, I don't found where to write the tests for the control. Any comment is welcome. 

**Issues with this control**

* All runs fine if you change value by keyboard. But ff you change the value from the function and the value is out of limits ( ex: value > Maximum ) the html control detects the mistake and an error appear if you place the mouse over the control but the red color for invalid input only appears on lost focus. 

Regards,
dani herrera.

### CODE REVIEW

**Comment by SamProf** [comment]
Hi!
Thank yo so much for your PR. This days, I have not enough time for cheking your source code and making release.
So, please give me few days to check, and make review.

**Comment by SamProf** [comment]
Hi!
As I right undastand you copy source code from MatTextField and add method to parse string value.
- It would be good if this component will have up and down buttons (not browser)
i - It would be good if this component will not copy source code, but at least use inheritance.

**Comment by ctrl-alt-d** [comment]
Hi Mr @SamProf , thanks about your review.

* I will rewrite component to have custom `+` and `-` buttons to increase and decrease number.
* I understand what you say about copy code. Inheritance will not be possible with new buttons.

Give me few days to rewrite control. 

Also, will be wonderful if you can create a branch (different of master) where to send my PRs, I'm not comfortable making PR's to master.

My team is writing a new internal ERP system and I guess we will need controls as TreeView, TreeGridView, CurrencyInput, ... I mean, if we write this controls, maybe, do you want to incorporate them to MatBlazor project or collaborate in some way.

Regards.

**Comment by SamProf** [comment]
I have no any problem to receive PR. If you will have some components and you want share your code by MIT license - it would ne good.
My opinion - it's difficult to make something great alone.
Ok, I will make `develop` branch.

**Pull request merged**
