### PR TITLE
Enables multiple file upload on MatFileInput component

### PR DESCRIPTION
**Pull request by jacomarcon**
The documentation for MatFileInput gives an example of being able to select or drop multiple files into the component for processing. The component currently only allows single file selection. This change enables the multiple file selection/drop into the component.

### CODE REVIEW

**Comment by jacomarcon** [comment]
Addresses issues #432, #435, and #489 .

**Comment by EduVencovsky** [comment]
I think that instead of just adding `multiple` it should be a bool parameter to decide if it's multiple or not.

**Comment by SamProf** [comment]
Nice feature
It would be good if multiple attribute will be optional.
What you think?

**Comment by RonPeters** [comment]
Agreed. Multiple should be an optional parameter passed to the component.

**Comment by jacomarcon** [comment]
Great idea, I'll wire that up and update the PR.

**Comment by enkodellc** [comment]
@jacomarcon please let me know the status of this PR. If you are going to update it or if it is already finished. Please use develop branch for the PR. When you are finished we will review. Thanks!

**Comment by jacomarcon** [comment]
Heya @enkodellc I've got it coded up, need to test/commit and I'll get it updated. Should have some time to work on it this upcoming weekend.

**Comment by enkodellc** [comment]
@jacomarcon just let us know when it is complete and we will review. Thanks!

**Comment by jacomarcon** [comment]
Changes to allow single or multiple file upload is complete. @enkodellc let me know if there is anything else I need to do to get it merged in.

**Comment by enkodellc** [comment]
Great, I will take a look at it soon, most likely tomorrow.

**Comment by enkodellc** [comment]
@jacomarcon I just did a quick code review. We appreciate your contribution! Next time please add a demo example for ease of testing. I will submit a PR for that.

**Pull request merged**
