### PR TITLE
Support arrow keys and Enter in Autocomplete

### LINKED ISSUE #211: [Future Request] MatAutocomplete - Use Arrow Keys and Enter to Select
It will be nice if the autocomplete can utilise the arrow Up and Down keys plus enter to navigate and select the options.

https://material.angular.io/components/autocomplete/examples

### PR DESCRIPTION
**Pull request by dga711**
Closes #211 

A basic js heavy implementation of supporting arrow keys and Enter in AutoComplete.

I tried many implementations from extending MDCList to sending Keyboard events. But this one works the best and should do the trick.

Just not 100% sure about the compatibility of sending the mouse event.

Please review.

### CODE REVIEW

**Comment by dga711** [comment]
I could add support for looping through the list when navigating over first and last item.

**Comment by dga711** [comment]
Thinking more about it I wonder if it would be better to put more logic into Blazor and work more with some JsInterop calls.
MatList could need SelectedIndex, SelectedItem etc. Then we could handle the key down events in Blazor and set the selection on MatList instead of this 100% JS solution.

**Comment by SamProf** [comment]
I just need more detailed see this PR. But the may of tricks I don't prefere. For me should be better way. I will check in a few days and then we will make decision.
Thank you!

**Comment by dga711** [comment]
Consider this WIP. I now figured out how to interop with the MDCList instance (saw it in your datepicker).
The plan is now to put 80% of the logic from JS to Blazor.

Will implement a SelectedIndex property to MatList (thats useful anyway). 
Then I will handle the keypress in BaseMatAutoComplete and adjust the selected item by setting the new property on MatList.

**Comment by dga711** [comment]
The key handling and logic is now in _MatAutoComplete_ instead of JS.
_MatList_ can now set and get the selectedindex via small interop.

Sadly I was not able to implement a _SelectedIndex_ Parameter because Properties can't be async and JSInterop dies when using .Result etc. on it.
https://github.com/aspnet/AspNetCore/issues/5553

**Comment by SamProf** [comment]
Hey! That's really good!
But only last one - when I select using keyboard item and press Enter - list should be closed I think.

**Pull request merged**
