### PR TITLE
Fix instantiation attempts for abstract types for multi column filtering in MatTable

### PR DESCRIPTION
**Pull request by akovac35**
I was receiving exceptions for abstract base types, the change in this pull request fixes the problem.

### CODE REVIEW

**Comment by SamProf** [comment]
@enkodellc What tou think bout this solution?

**Comment by enkodellc** [comment]
Well the code looks clean and elegant. It would be beneficial to see what @akovac35  was doing to get the exceptions.  The code seems to work so I have no other opinion except to change it from master to develop.

**Comment by akovac35** [comment]
I was only doing a multi column filtering on nullable value columns. Both my pull requests together enable multicolumn filtering to work properly. I haven’t gone into more details though, just made the fix so I can continue my stuff :)

**Comment by akovac35** [comment]
Aj, sorry, that is for the other pull request. Yes, so, I had an abstract base class, which was used as item type, and a list of concrete type variants. The code tried to instantate the abstract class...

**Comment by akovac35** [comment]
Can I assist with merging? As I have written, not all item types are concrete types. Instantiating item types just to get type properties will not always work.

**Review by enkodellc — APPROVED** [review]

**Pull request merged**
