### PR TITLE
Adjusted all @functions to @code.

### PR DESCRIPTION
**Pull request by SeppPenner**
The call to `@functions` should be changed to `@code` following https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/.

Fixes https://github.com/SamProf/MatBlazor/issues/209.

### CODE REVIEW

**Comment by SeppPenner** [comment]
> To upgrade an existing ASP.NET Core 3.0 Preview 5 project to Preview 6:
> ...
> In Blazor apps:
> Rename @functions to @code

**Comment by SeppPenner** [comment]
I don't know how the docs are done here but I assume that the need to be changed as well.

**Comment by SamProf** [comment]
Thank you for your contribution.
The reason why I don't make it before - Resharper still don't support `@code` block.
I will merge this PR sometimes later.

**Comment by SeppPenner** [comment]
> Thank you for your contribution.
> The reason why I didn't makeit before - Resharper still doesn't support support `@code` block.
> I will merge this PR sometimes later.

Ah okay. I didn't even know that there is a version of Resharper for VS preview already :D

**Comment by SeppPenner** [comment]
@SamProf It might be that you have an outdated version of Resharper... The latest version (2019.2.2) I have, doesn't complain about `@code`.

**Comment by SeppPenner** [comment]
Sorry, I did some bullshit here and deleted the branch... The new pull request regarding this is under https://github.com/SamProf/MatBlazor/pull/233.

**Pull request closed without merging**
